baseURL = "https://www.rebornthroughpain.com/"
languageCode = "en-us"
title = "Reborn Through Pain"
theme = "RTP"


[params]

headerImg = "https://bulma.io/images/bulma-type-white.png"
heroTitle = "Living The Life of Your Dreams is Simpler Than You Think"
heroSubtitle = '''Don’t get it twisted. I said SIMPLER not EASIER.
                IF you’re not willing to put in the work stop right here and go back to buzzfeed.
                Seeing that you’re still here. You want to step up in life.
                Check out the blog for the types of articles that will make you
                grab your nuts in public and slap the gums of an old lady for
                eye your subway seat. (not really)'''
author= "Abdoulaye"


[menu]
    [[menu.main]]
        identifier = "about"
        name = "New? Start Here!"
        title = "New? Start Here!"
        weight = 1
        url = "/about"
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        title = "Blog"
        weight = 2
        url = "/blog"
    [[menu.main]]
        identifier = "contact"
        name = "Get In Touch"
        title = "Contact"
        weight = 4
        url = "/contact"
    [[menu.main]]
        identifier = "books"
        name = "Book Reviews"
        title = "Book Reviews"
        weight = 3
        url = "/book-reviews"
